version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - HF_HUB_DISABLE_XET=True  # Suppress hf_xet warning
    networks:
      - app-network
  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - app-network
networks:
  app-network:
    driver: bridge